# Inserts a blank line between shell prompts

"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
command_timeout = 15

[aws]
style = "bold #ffb86c"

[character]
error_symbol = "[λ](bold #ff5555)"
success_symbol = "[λ](bold #50fa7b)"
vicmd_symbol = "[V](bold green)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"
truncation_length = 8
truncation_symbol = "../"
truncate_to_repo  = false

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #bd93f9"

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"

[package]
disabled = true

[python]
disabled = true

[time]
time_format = '%T'
disabled = false

[kubernetes]
format = 'on k8s ($user on )($cluster in )$context \($namespace\)](dimmed green) '
disabled = false

[env_var.KUBECONFIG]
default = ''
style = 'dimmed green'
format = "\n$env_value ($style)"
disabled = false

[container]
format = '[$symbol \[$name\]]($style) '
disabled = false

